repos:
  - repo: https://github.com/pocc/pre-commit-hooks
    rev: v1.3.5
    hooks:
      - id: clang-tidy
        args: [--config-file=.clang-tidy]
        files: '^orion/.*\.(h|cc)$'
      - id: cppcheck
        args:
            - --language=c++
            - --std=c++20
            - --enable=warning,style,performance,portability
            - --suppress=missingIncludeSystem
            - --suppress=unusedStructMember
            - --inline-suppr
            - --error-exitcode=1
        files: '^orion/.*\.(h|cc)$'
