repos:
  - repo: https://github.com/pocc/pre-commit-hooks
    rev: v1.3.5
    hooks:
      - id: clang-tidy
        args: [--config-file=.clang-tidy]
        files: '^orion/.*\.(h|cc)$'
      - id: cppcheck
        args: [--enable=warning,style,performance,portability, --std=c++17, --inline-suppr]
        files: '^orion/.*\.(h|cc)$'
